### ISSUE TITLE
HTML / CSS Issues

### ISSUE THREAD

**Issue by jshet** [mdbloice/Labeller#1]
Hi, first of all, thank you for making and sharing this!
It's EXACTLY what I was looking for. 
(I tried several other tools and they were not working for what I wanted.)

Question: I've restyled the template and styles/dashboard.css to be a bit cleaner and bigger, do you want to see any of the changes? Are you interested in my doing a bit cleaner of a rewrite?

(It currently looks like in the attached screenshot.)

<img width="1728" alt="image" src="https://github.com/mdbloice/Labeller/assets/59068399/ccb7301d-da21-4a79-8b28-80ea67ea7eba">

**Comment by jshet** [comment]
Update: it looks like this now. 
<img width="1728" alt="image" src="https://github.com/mdbloice/Labeller/assets/59068399/f33bc6e8-41ee-412f-855e-403cbc1ba756">

**Comment by jshet** [comment]
UPDATE: Ok, so I decided to dive into the generator portion a bit and get things fixed up. 
This is now a working design:

<img width="1728" alt="image" src="https://github.com/mdbloice/Labeller/assets/59068399/5a437b02-021f-4695-9ba7-664764d29755">

**Comment by mdbloice** [comment]
Hi @jshet - glad you like the package. That looks great, do you wanna make a PR so we can perhaps integrate your changes? 

M.

**Comment by jshet** [comment]
Sounds good.
Here you go:
#2

**Comment by mdbloice** [comment]
Hi ok, so #2  has been merged, thanks a lot for the efforts!
